config/routes.rb
Rails.application.routes.draw do

  resources :responses

  resources :asks

  get 'password_resets/new'

  get 'password_resets/edit'

  get '/auth/:provider/callback', to: 'oauth#callback', as: 'oauth_callback'
  get '/auth/failure', to: 'oauth#failure', as: 'oauth_failure'
  get 'users/new'
  root                'static_pages#home'
  get    'contact'  => 'static_pages#contact'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get    'access_event'   => 'events#_access'
  get '/events/:id/attendees', to: 'events#attendees', as: 'attendees'
  post    'validate_access'   => 'events#validate_access'
  get    'register'  => 'users#new'

  resources :asks 
  resources :responses 
  resources :users 
  resources :events
  resources :attendance_histories
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

end

app/models/ask.rb
class Ask < ActiveRecord::Base
  belongs_to :user
  belongs_to :event

  has_many :responses

  validates :ask,  presence: true
  validates :user,  presence: true
  validates :event,  presence: true
  
  default_scope -> { order(created_at: :desc) }
end

app/controllers/asks_controller.rb
class AsksController < ApplicationController
  before_action :set_ask, only: [:show, :edit, :update, :destroy]
  #before_action :set_event, only: [ :edit, :new]

  # GET /asks
  # GET /asks.json
  def index
    @asks = Ask.all
  end

  # GET /asks/1
  # GET /asks/1.json
  def show
    responses = @ask.responses.paginate(page: params[:page])
  end

  # GET /asks/new
  def new
    @ask = Ask.new(event_id: params[:event_id])
  end

  # GET /asks/1/edit
  def edit
  end

  # POST /asks
  # POST /asks.json
  def create
    @ask = Ask.new(ask_params)

    respond_to do |format|
      if @ask.save
        format.html { flash[:success] =  'Ask was successfully created.'
         redirect_to @ask.event }
        format.json { redirect_to @ask.event, status: :created, location: @ask }
      else
        format.html { flash[:danger] = 'Sorry, the ask could not be created.'
          redirect_to @ask.event }
        format.json { render json: @ask.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /asks/1
  # PATCH/PUT /asks/1.json
  def update
    respond_to do |format|
      if @ask.update(ask_params)
        format.html { redirect_to @ask, notice: 'Ask was successfully updated.' }
        format.json { render :show, status: :ok, location: @ask }
      else
        format.html { render :edit }
        format.json { render json: @ask.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /asks/1
  # DELETE /asks/1.json
  def destroy
    @ask.destroy
    respond_to do |format|
      format.html { redirect_to asks_url, notice: 'Ask was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ask
      @ask = Ask.find(params[:id])
    end
    def set_event
      @event = Event.find(params[:event_id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def ask_params
      params.require(:ask).permit(:user_id, :event_id, :ask, :details)
    end
end

app/helpers/asks_helper.rb
module AsksHelper

	# def card_colors
	# 	 ['91CFFF', '88D0E0', '6EA8A7', 'FFD090', 'F1BBA7', '0DC59C']
	# end
	def get_card_color(card_colors)
		next_color = card_colors.shift
		card_colors.push(next_color)
		return card_colors
	end
end

app/views/asks/_ask.html.erb
	<div class="ask" id="ask-<%= ask.id %>">
		<div class="ask-section">
			<small class="timestamp">
				<%= time_ago_in_words(ask.created_at) %> ago.
			</small>
			<%=  gravatar_for ask.user %> 			
			<span class="user">
				<%= link_to ask.user.firstName + ' ' + ask.user.lastName.first, ask.user, class:"ask-user-name" %>
			</span>	

			<span class="content"><%= ask.ask %></span>


		<br>
		<a class="" role="button" data-toggle="collapse" href="#collapse-<%= ask.id %>" aria-expanded="true" aria-controls="collapse">
			
			<div class="response_count"> <%= ask.responses.count %> <%= "Comment".pluralize(ask.responses.count) %></div>
		</a>



		</div>


		<div class="collapse" id="collapse-<%= ask.id %>">


		
		<!-- Inline response form -->
		<div class="inline-response-form">
			<% @response=Response.new %>
			<%= form_for(@response, html:{class:"form-inline"}) do |f| %>
			<% if @response.errors.any? %>
			<div id="error_explanation">
				<h2><%= pluralize(@response.errors.count, "error") %> prohibited this response from being saved:</h2>

				<ul>
					<% @response.errors.full_messages.each do |message| %>
					<li><%= message %></li>
					<% end %>
				</ul>
			</div>
			<% end %>


			<%= f.hidden_field :user_id, :value => current_user.id%>
			<%= f.hidden_field :ask_id, :value => ask.id %>
			<span class="">
				<%= f.text_area :response, placeholder: "Respond to question here.", class: 'w-input' %>
			</span>
			<span class="">
				<%= f.submit "Submit", class:"btn btn-default" %>
			</span>
			<% end %>
		</div>

		<!-- end of Inline response form -->

			<div class="responses">
				<br>
				<% if ask.responses.any? %>
				<% ask.responses.each do |response| %>
				<div class="response">
					<%= render response %>
				</div>
				<% end %>
				<% end %>  
			</div>
		</div>


	</div>

app/views/asks/_form.html.erb
<br><br><br>
<div class="w-container">
  <div class="col-md-6 col-md-offset-3 form-wrapper w-form">

<%= form_for(@ask) do |f| %>
  <% if @ask.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ask.errors.count, "error") %> prohibited this ask from being saved:</h2>

      <ul>
      <% @ask.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <%= f.hidden_field :user_id, :value => current_user.id%>
  <%= f.hidden_field :event_id %>
  <div class="field">
    <%= f.text_field :ask, placeholder: "Ask your question here.", class: 'form-field w-input' %>
  </div>
  <div class="field">
    <%= f.text_area :details, placeholder: "Add details here", class: 'form-field w-input' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
  </div>
  </div>

app/views/asks/edit.html.erb
<h1>Editing Ask</h1>

<%= render 'form' %>

<%= link_to 'Show', @ask %> |
<%= link_to 'Back', asks_path %>

app/views/asks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Asks</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Event</th>
      <th>Ask</th>
      <th>Details</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @asks.each do |ask| %>
      <tr>
        <td><%= ask.user %></td>
        <td><%= ask.event %></td>
        <td><%= ask.ask %></td>
        <td><%= ask.details %></td>
        <td><%= link_to 'Show', ask %></td>
        <td><%= link_to 'Edit', edit_ask_path(ask) %></td>
        <td><%= link_to 'Destroy', ask, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ask', new_ask_path %>

app/views/asks/new.html.erb
<h1>New Ask</h1>

<%= render 'form' %>

<%= link_to 'Back', asks_path %>

app/views/asks/show.html.erb
<br><br><br>
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @ask.user.firstName %>   <%= @ask.user.lastName %>
</p>

<p>
  <strong>Event:</strong>
  <%= @ask.event.name %>
</p>

<p>
  <strong>Ask:</strong>
  <%= @ask.ask %>
</p>

<p>
  <strong>Details:</strong>
  <%= @ask.details %>
</p>

<%= link_to "Respond to Ask", new_response_path(ask_id: @ask.id), class: "navigation-link w-nav-link" %>
<%= link_to 'Edit', edit_ask_path(@ask) %> |
<%= link_to 'Back', asks_path %>