config/routes.rb
Rails.application.routes.draw do

  resources :responses

  resources :asks

  get 'password_resets/new'

  get 'password_resets/edit'

  get '/auth/:provider/callback', to: 'oauth#callback', as: 'oauth_callback'
  get '/auth/failure', to: 'oauth#failure', as: 'oauth_failure'
  get 'users/new'
  root                'static_pages#home'
  get    'contact'  => 'static_pages#contact'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get    'access_event'   => 'events#_access'
  get '/events/:id/attendees', to: 'events#attendees', as: 'attendees'
  post    'validate_access'   => 'events#validate_access'
  get    'register'  => 'users#new'

  resources :asks 
  resources :responses 
  resources :users 
  resources :events
  resources :attendance_histories
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

end

app/models/event.rb
class Event < ActiveRecord::Base
	before_create :set_access_code
	has_many :users, through: :attendance_histories
	has_many :attendance_histories
	has_many :asks
	belongs_to :user

	#  has_many :event_check_ins
	#  mount_uploader :picture, PictureUploader
	validates :startDate,  presence: true
	validates :endDate,  presence: true
	validates :name,  presence: true
	validate :start_date_is_today_or_later
	validate :end_date_is_after_start_date
  
  # def to_param
  #   "#{name}-#{access_code}"
  # end

  def send_event_details
    UserMailer.event_details(self).deliver_now
  end
private

	def start_date_is_today_or_later
	  return if startDate.blank?

	  if startDate < Date.today
	    errors.add(:startDate, "cannot be in the past") 
	  end 
	end
	def end_date_is_after_start_date
	  return if endDate.blank? || startDate.blank?

	  if endDate < startDate
	    errors.add(:endDate, "cannot be before the start date") 
	  end 
	end

	def generate_access_code
		o = [('A'..'Z')].map { |i| i.to_a }.flatten
		loop do
			code = (0...6).map { o[rand(o.length)] }.join
			break code unless self.class.find_by(access_code: code)
		end
	end

	def set_access_code
		write_attribute(:access_code, generate_access_code)
	end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy, :attendees]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
   
  end

  def attendees
    @attendees = @event.users
  end

  def access 
    @event = Event.new
  end

  def validate_access
    @event = Event.where(["access_code = ? and 'endDate' >= ? ", params[:event][:access_code],Date.today])
    if !@event.empty?
      @attendance = AttendanceHistory.new(user: current_user, event: @event.first) 
      @attendance.save! if !AttendanceHistory.find_by(user: current_user, event: @event.first)
      redirect_to @event.first
    else
      flash[:danger] = 'Access code not found. Please contact your organizer.' 
      redirect_to events_path
    end

  end


  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
      @event.send_event_details
        format.html { flash[:success] = 'Event was successfully created.'
          redirect_to @event }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { flash[:danger] = 'Event could not be created.'
          render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { flash[:success] = 'Event was successfully updated.'
          redirect_to @event }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { flash[:danger] = 'Sorry, event could not be updated.'
          render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { flash[:success] = 'Event was successfully destroyed'
        redirect_to events_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :description, :user_id, :picture, :url, :startDate, :endDate)
    end
end

app/helpers/events_helper.rb
module EventsHelper

end

app/views/events/_access.html.erb
<div class ="event_access_form">
	<% @event = Event.new %>
	<%= form_for @event, :url => validate_access_path do |f| %>

	<div class="field">
		<%= f.text_field :access_code, placeholder: "Access Code", class: 'form-field w-input' %>
	</div>


	<div class="actions">
		<%= f.submit "Enter Room", class: "button full-width w-button event_access_button" %>
	</div>
	<% end %>
</div>

app/views/events/_form.html.erb
<div class="w-container">
  <div class="col-md-6 col-md-offset-3 form-wrapper w-form">

    <%= form_for(@event) do |f| %>

    <br>
    <br>
    <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>


    <%= f.hidden_field :user_id, :value => current_user.id%>


    <div class="field">
      <%= f.text_field :name, placeholder: "Name", class: 'form-field w-input' %>
    </div>
    <div class="field">
      <%= f.text_field :description, placeholder: "Description", class: 'form-field w-input' %>
    </div>
    <div class="field">
      <%= f.text_field :picture, placeholder: "Picture", class: 'form-field w-input' %>
    </div>
    <div class="field">
      <%= f.text_field :url, placeholder: "Url", class: 'form-field w-input' %>
    </div>
    <div class="field">
      <%= f.text_field :startDate, placeholder: "Start Date", 'data-behaviour' => 'datepicker', 'data-provide'=> 'datepicker', class: 'datepicker form-field w-input datetimepicker4', :value => @event.startDate ? @event.startDate.strftime("%d-%m-%Y %I:%M %p") : ''  %>
    </div>
    <div class="field">
      <%= f.text_field :endDate, placeholder: "End Date", 'data-behaviour' => 'datepicker', 'data-provide'=> 'datepicker', class: 'datepicker form-field w-input datetimepicker4', :value =>  @event.endDate ? @event.endDate.strftime("%d-%m-%Y %I:%M %p") : ''  %>
    </div>
    <div class="actions">
      <%= f.submit "Create Event", class: "button full-width w-button" %>
    </div>
    <% end %>

  </div>
</div>

<script type="text/javascript">
$(function () {
  $('.datetimepicker4').datetimepicker({
    format: 'DD-MM-YYYY HH:mm A',
    sideBySide: true,
    showClose: true,
    widgetPositioning: {
      horizontal: 'auto',
      vertical: 'bottom'
    },
    stepping: 5
  });
});
</script>

app/views/events/attendees.html.erb
<% provide(:title, 'Attendees') %>
<br><br><br><br><br><br>
<h1>Event Attendees</h1>

<ul class="users">
  <% @attendees.each do |attendee| %>
    <li>
      <%= link_to attendee.firstName + ' ' + attendee.lastName, attendee %>
    </li>
  <% end %>
</ul>

app/views/events/edit.html.erb
<br>
<br>
<br>
<br><h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<% provide(:title, "Events") %>
<% provide(:mobile_header_title, "Events") %>
<% provide(:bodyclass, "events_index") %>



<br>

<br>
<br>

<div class="events_container">

  <h1>Events</h1>

<div class="explanation"> Add events by entering the unique room code from your email. Enter room to see who is there and how you can help them.
</div>
  <%= render "access" %>
</div>

<% if logged_in? %>
  <% if !current_user.events.empty? %>
    <div class="events_list events_container">
      <h1>My Rooms</h1>
        <% current_user.events.each do |event| %>
          <div class="room-list-item">
            <div class="room-name"><%= event.name %></div>
            <div class="room-owner">
              By: <%= event.user.firstName %> <%= event.user.lastName %><br>
              On: <%= event.startDate.strftime("%b %d, %Y") %>
            </div>
            <%= link_to "Enter Room", event_path(event), class: "btn btn-success room-btn" %>
          </div>
        <% end %>
    </div>
  <% end %>
<% end %>
<br><br><br><br>


<% if current_user.admin? %>
<h2 class="centered section-heading">Admins Only View: Events</h2>
  <table class="table table-condensed">
    <thead>
      <tr>
        <th>Name</th>
        <th>Access Code</th>
        <th>Start date</th>
        <th>End date</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @events.each do |event| %>
      <tr>
        <td><%= event.name %></td>
        <td><%= event.access_code %></td>
        <td><%= event.startDate %></td>
        <td><%= event.endDate %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
<br>
<%= link_to 'New Event', new_event_path %>
<% end %>

app/views/events/new.html.erb
<% provide(:title, 'Create New Event') %>
<br>
<br>
<br>
<br>

<h2 class="centered section-heading">Create New Event</h2>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<% provide(:title, @event.name) %>
<% provide(:mobile_header_title, @event.name) %>
<% provide(:bodyclass, "event_body") %>

<div class="event_head wrap" >
  <div class="event_host">
    Host: <%= @event.user.firstName %>  <%= @event.user.lastName %>
  </div>

    <div class="event_name">
      <%= @event.name %>
    </div>
    <div class="event_details">
      <%= @event.startDate.strftime("%a %b %d at %I:%M%p") %>
    </div>

    <div class="event_my_stats">
      <div class="event_my_stats_section">
        <div class= "circle"> 
          <div class= "circle_value"> 
            <%= @event.asks(user: current_user).count %>
          </div>
        </div>
        My Asks
      </div>
      <div class="event_my_stats_section">
        <div class= "circle">
          <div class= "circle_value"> 
            <%= current_user.responses(event: @event).count %>
          </div>
        </div>
        My Answers
      </div>
      <div class="event_my_stats_section">
        <div class= "circle">
          <div class= "circle_value"> 
            <%= current_user.responses.count %>
          </div>
        </div>
        My Points
      </div>
    </div>


  <div class="ask_button" id="ask_button" >
    <div id="ask_container" title = 'Create an Ask' 'data-toggle' = 'tooltip' 'data-placement' = 'right'>
      <span>
      <%= link_to image_tag("icons/add-ask-button-60x60@2x.png", border: 0), '#', id:"ask_button_img", 'data-toggle' => "modal", 'data-target' => "#myModal" %>
    </span>
    </div>
  </div>

  <!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
          <% @ask = Ask.new %>
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">What are you looking for?</h4>
        </div>
        <div class="modal-body">
          <%= form_for(@ask) do |f| %>
            <% if @ask.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@ask.errors.count, "error") %> prohibited this ask from being saved:</h2>

                <ul>
                <% @ask.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
                </ul>
              </div>
            <% end %>


            <%= f.hidden_field :user_id, :value => current_user.id%>
            <%= f.hidden_field :event_id, :value => @event.id %>
            <div class="field">
              <%= f.text_area :ask, placeholder: "Ask your question here.", class: 'form-field w-input no-bottom-margin' %>
            </div>
            <br>
              <%= f.submit "Submit", class: "btn btn-info modal-btn" %>
          <% end %>
        </div>
      </div>
      
    </div>
  </div>
  




  <div class="event_tabs">
    <%= link_to 'ASKS (' + @event.asks.count.to_s + ')', '#', id:"focusmeplease", class: "event_tab event_asks_tab", onclick: "openContent(event, 'asks_panel')" %> 
    <%= link_to 'PEOPLE (' + @event.users.count.to_s + ')', '#', class: "event_tab event_attendees_tab", onclick: "openContent(event, 'attendees_panel')" %>
  </div>
</div>

<div id="asks_panel" class="tabcontent" event_attendees_tab>
<% card_colors = ['91CFFF', '88D0E0', '6EA8A7', 'FFD090', 'F1BBA7', '0DC59C'] %>
  <% if @event.asks.any? %>
    <% @event.asks.each do |ask| %>
    <div class="asks" style="background-color: #<%= get_card_color(card_colors).first %>;">
      <%= render ask %>
    </div>
    <% end %>
  <% end %>
</div>



<div id="attendees_panel" class="tabcontent", style="display:none;">
<% card_colors = ['91CFFF', '88D0E0', '6EA8A7', 'FFD090', 'F1BBA7', '0DC59C'] %>
  <% if @event.users.any? %>
    <% @event.users.each do |attendee| %>
    <div class="attendees">
      <%= render attendee %>
    </div>
    <% end %>
  <% end %>
</div>