config/routes.rb
Rails.application.routes.draw do

  resources :responses

  resources :asks

  get 'password_resets/new'

  get 'password_resets/edit'

  get '/auth/:provider/callback', to: 'oauth#callback', as: 'oauth_callback'
  get '/auth/failure', to: 'oauth#failure', as: 'oauth_failure'
  get 'users/new'
  root                'static_pages#home'
  get    'contact'  => 'static_pages#contact'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get    'access_event'   => 'events#_access'
  get '/events/:id/attendees', to: 'events#attendees', as: 'attendees'
  post    'validate_access'   => 'events#validate_access'
  get    'register'  => 'users#new'

  resources :asks 
  resources :responses 
  resources :users 
  resources :events
  resources :attendance_histories
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

end

app/views/layouts/_footer.html.erb
		<footer class="footer">
			<div class="w-container">
				<div class="w-row">
					<div class="spc w-col w-col-4">
						<h5>about US
						</h5>
						<p>Lynx was conceived in 2015 by Enhao Li &amp; Xuan Yue in the effort to address the current day frustrations with professional networking.&nbsp;
						</p>
					</div>
					<div class="spc w-col w-col-4">
						<h5>Our AFFILIATES
						</h5>
						<a class="footer-link" href="http://runway.is">RUNWAY
						</a>
						<a class="footer-link" href="http://www.meetup.com/InfluenceOthers">RESOURCE CENTER - SCIENTIFIC MARKETING
						</a>
						<a class="footer-link" href="http://www.pincc.org">PINCC
						</a>
					</div>
					<div class="w-col w-col-4">
						<h5>social
						</h5>
						<div class="footer-link-wrapper w-clearfix">
							<img class="info-icon" src="http://uploads.webflow.com/5708403cc3aa1ecb51b0c5a4/5708403cc3aa1ecb51b0c5cb_social-18.svg" width="20">
							<a class="footer-link with-icon" href="http://www.twitter.com/hellolynx">Twitter
							</a>
						</div>
						<div class="footer-link-wrapper w-clearfix">
							<img class="info-icon" src="http://uploads.webflow.com/5708403cc3aa1ecb51b0c5a4/5708403cc3aa1ecb51b0c5ba_social-03.svg" width="20">
							<a class="footer-link with-icon" href="http://www.facebook.com/lynxnetworking">Facebook
							</a>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="center footer">
			<div class="w-container">
				<div class="footer-text">Copyright Lynx 2016
				</div>
			</div>
		</footer>

app/views/layouts/_header.html.erb
<div id="nav" class="navigation-bar w-nav" data-animation="default" data-collapse="medium" data-contain="1" data-duration="400">
  <div class="w-container">
    <a class="brand-link w-nav-brand" href="/">

      <%= image_tag "lynx-gray.png", alt: "Picture", style: "width:40px" %>
    </a>
    <nav class="navigation-menu w-nav-menu" role="navigation">
      <% if logged_in?%>
        <%= link_to "Log Out", logout_path, method: "delete", class: "navigation-link w-nav-link" %>
        <%= link_to "Events", events_path, class: "navigation-link w-nav-link" %>
      <%else%>
        <%= link_to "Log In", login_path, class: "navigation-link w-nav-link" %>
      <%end%>
      <a class="navigation-link w-nav-link" href="/contact">Contact</a>
    </nav>
    <div class="hamburger-button w-nav-button" onclick="openNav()">
      <div class="w-icon-nav-menu">
      </div>
    </div>
  </div>
</div>

app/views/layouts/_shim.html.erb
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/_sidenav.html.erb
<div id="mySidenav" class="sidenav">
      <% if logged_in?%>
        <%= link_to "Log Out", logout_path, method: "delete", class: "navigation-link w-nav-link" %>
        <%= link_to "Events", events_path, class: "navigation-link w-nav-link" %>
      <%else%>
        <%= link_to "Log In", login_path, class: "navigation-link w-nav-link" %>
        <%= link_to "Sign Up", signup_path, class: "navigation-link w-nav-link" %>
      <%end%>
      <a class="navigation-link w-nav-link" href="/contact">Contact</a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>

  <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.4.7/webfont.js">
  </script>
  <script type="text/javascript">WebFont.load({
    google: {
      families: ["Open Sans:300,300italic,400,400italic,600,600italic,700,700italic,800,800italic","Montserrat:400,700","Varela:400","Roboto:300,regular,500"]
    }
  });
  </script>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <%= render 'layouts/shim' %>
</head>
<body id="wrap">
  <%= render 'layouts/sidenav' %>
  <%= render 'layouts/header' %>
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
  <div class="<%=yield(:bodyclass)%>">
    <%= yield %>
  </div>
  <%= debug(params) if Rails.env.development? %>
</body>
</html>